### ISSUE TITLE
Looking to get some help.

### ISSUE THREAD

**Issue by lucifer911** [ADAPhilippines/ADAPH.TxSubmit#1]
Hey, Nice project. I am not good with developing and stuff. I was wondering If I there is a way for you to send me a guide about how to set this up.
Thank you.

**Comment by starlit-rocketship** [comment]
Yea I too would love a bit of a guide :)

**Comment by Mercurial** [comment]
https://github.com/ADAPhilippines/ADAPH.TxSubmit/blob/master/README.md here you go let me know if you guys have any questions.

**Comment by lucifer911** [comment]
Thank you, Going to set it up.

**Comment by lucifer911** [comment]
I cant DM you on twitter, that is why i am posting here.

When I run 
sudo dotnet ef database update

I get this error.

Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-ef does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.

**Comment by starlit-rocketship** [comment]
I too get the the error as stated by lucifer911 above

**Comment by Mercurial** [comment]
ah yes forgot to mention you need to add `export PATH="$PATH:$HOME/.dotnet/tools"` to `.bashrc` will add it in the readme
