### ISSUE TITLE
Specifying the Uri in Program.cs

### ISSUE THREAD

**Issue by btbf** [ADAPhilippines/ADAPH.TxSubmit#3]
Do I need to customize this URL?
https://github.com/ADAPhilippines/ADAPH.TxSubmit/blob/70fcd452805f655b7c037b934df8c2b23a3ed31c/Program.cs#L49

**Comment by Mercurial** [comment]
So right now we use this service for `TxTracking` and that feature is not yet fully completed so we rely on our own hosted service temporarily. But later on we want this to be part of the TxSubmit service or a separate open source project.

in your `appsettings.json` if you have the option `"TxTracking": false` set to false then it should not matter. you can leave this alone

If you want transaction tracking feature then for now you will have to rely on our service (the one in the URL).

<img width="1236" alt="image" src="https://user-images.githubusercontent.com/585569/155351680-cbd2f206-661e-429b-ab0c-28e17f17208d.png">

**Comment by btbf** [comment]
I Understand.
Thank you!
